runtime: nodejs16 # or another supported version
service: arweave-verto-testnet
instance_class: F4_1G

automatic_scaling:
  min_instances: 3
  max_instances: 6
  min_pending_latency: 1000ms
  max_pending_latency: 3000ms
  target_cpu_utilization: 0.8
