runtime: nodejs16 # or another supported version
service: arweave-verto-testnet
instance_class: F4_1G

automatic_scaling:
  min_instances: 1
  max_instances: 1
  min_pending_latency: 2000ms
  max_pending_latency: 4000ms
